#!/usr/bin/perl

# DO NOT EDIT THIS FILE - update __DATA__ section of helper_script/regen_openssl_constants.pl

use strict;
use warnings;
use Net::SSLeay;

eval "use Test::Exception;";
if ($@)
{
    eval "use Test::More skip_all => 'Some tests need Test::Exception';";
}
else
{
    eval 'use Test::More tests => 465;';
}

my @c = (qw/
 ASN1_STRFLGS_ESC_CTRL           NID_id_qt_cps                          OP_NO_QUERY_MTU
 ASN1_STRFLGS_ESC_MSB            NID_id_qt_unotice                      OP_NO_RENEGOTIATION
 ASN1_STRFLGS_ESC_QUOTE          NID_idea_cbc                           OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION
 ASN1_STRFLGS_RFC2253            NID_idea_cfb64                         OP_NO_SSL_MASK
 CB_ACCEPT_EXIT                  NID_idea_ecb                           OP_NO_SSLv2
 CB_ACCEPT_LOOP                  NID_idea_ofb64                         OP_NO_SSLv3
 CB_ALERT                        NID_info_access                        OP_NO_TICKET
 CB_CONNECT_EXIT                 NID_initials                           OP_NO_TLSv1
 CB_CONNECT_LOOP                 NID_invalidity_date                    OP_NO_TLSv1_1
 CB_EXIT                         NID_issuer_alt_name                    OP_NO_TLSv1_2
 CB_HANDSHAKE_DONE               NID_keyBag                             OP_NO_TLSv1_3
 CB_HANDSHAKE_START              NID_key_usage                          OP_PKCS1_CHECK_1
 CB_LOOP                         NID_localKeyID                         OP_PKCS1_CHECK_2
 CB_READ                         NID_localityName                       OP_PRIORITIZE_CHACHA
 CB_READ_ALERT                   NID_md2                                OP_SAFARI_ECDHE_ECDSA_BUG
 CB_WRITE                        NID_md2WithRSAEncryption               OP_SINGLE_DH_USE
 CB_WRITE_ALERT                  NID_md5                                OP_SINGLE_ECDH_USE
 ERROR_NONE                      NID_md5WithRSA                         OP_SSLEAY_080_CLIENT_DH_BUG
 ERROR_SSL                       NID_md5WithRSAEncryption               OP_SSLREF2_REUSE_CERT_TYPE_BUG
 ERROR_SYSCALL                   NID_md5_sha1                           OP_TLSEXT_PADDING
 ERROR_WANT_ACCEPT               NID_mdc2                               OP_TLS_BLOCK_PADDING_BUG
 ERROR_WANT_CONNECT              NID_mdc2WithRSA                        OP_TLS_D5_BUG
 ERROR_WANT_READ                 NID_ms_code_com                        OP_TLS_ROLLBACK_BUG
 ERROR_WANT_WRITE                NID_ms_code_ind                        READING
 ERROR_WANT_X509_LOOKUP          NID_ms_ctl_sign                        RECEIVED_SHUTDOWN
 ERROR_ZERO_RETURN               NID_ms_efs                             RSA_3
 EVP_PKS_DSA                     NID_ms_ext_req                         RSA_F4
 EVP_PKS_EC                      NID_ms_sgc                             R_BAD_AUTHENTICATION_TYPE
 EVP_PKS_RSA                     NID_name                               R_BAD_CHECKSUM
 EVP_PKT_ENC                     NID_netscape                           R_BAD_MAC_DECODE
 EVP_PKT_EXCH                    NID_netscape_base_url                  R_BAD_RESPONSE_ARGUMENT
 EVP_PKT_EXP                     NID_netscape_ca_policy_url             R_BAD_SSL_FILETYPE
 EVP_PKT_SIGN                    NID_netscape_ca_revocation_url         R_BAD_SSL_SESSION_ID_LENGTH
 EVP_PK_DH                       NID_netscape_cert_extension            R_BAD_STATE
 EVP_PK_DSA                      NID_netscape_cert_sequence             R_BAD_WRITE_RETRY
 EVP_PK_EC                       NID_netscape_cert_type                 R_CHALLENGE_IS_DIFFERENT
 EVP_PK_RSA                      NID_netscape_comment                   R_CIPHER_TABLE_SRC_ERROR
 FILETYPE_ASN1                   NID_netscape_data_type                 R_INVALID_CHALLENGE_LENGTH
 FILETYPE_PEM                    NID_netscape_renewal_url               R_NO_CERTIFICATE_SET
 F_CLIENT_CERTIFICATE            NID_netscape_revocation_url            R_NO_CERTIFICATE_SPECIFIED
 F_CLIENT_HELLO                  NID_netscape_ssl_server_name           R_NO_CIPHER_LIST
 F_CLIENT_MASTER_KEY             NID_ns_sgc                             R_NO_CIPHER_MATCH
 F_D2I_SSL_SESSION               NID_organizationName                   R_NO_PRIVATEKEY
 F_GET_CLIENT_FINISHED           NID_organizationalUnitName             R_NO_PUBLICKEY
 F_GET_CLIENT_HELLO              NID_pbeWithMD2AndDES_CBC               R_NULL_SSL_CTX
 F_GET_CLIENT_MASTER_KEY         NID_pbeWithMD2AndRC2_CBC               R_PEER_DID_NOT_RETURN_A_CERTIFICATE
 F_GET_SERVER_FINISHED           NID_pbeWithMD5AndCast5_CBC             R_PEER_ERROR
 F_GET_SERVER_HELLO              NID_pbeWithMD5AndDES_CBC               R_PEER_ERROR_CERTIFICATE
 F_GET_SERVER_VERIFY             NID_pbeWithMD5AndRC2_CBC               R_PEER_ERROR_NO_CIPHER
 F_I2D_SSL_SESSION               NID_pbeWithSHA1AndDES_CBC              R_PEER_ERROR_UNSUPPORTED_CERTIFICATE_TYPE
 F_READ_N                        NID_pbeWithSHA1AndRC2_CBC              R_PUBLIC_KEY_ENCRYPT_ERROR
 F_REQUEST_CERTIFICATE           NID_pbe_WithSHA1And128BitRC2_CBC       R_PUBLIC_KEY_IS_NOT_RSA
 F_SERVER_HELLO                  NID_pbe_WithSHA1And128BitRC4           R_READ_WRONG_PACKET_TYPE
 F_SSL_CERT_NEW                  NID_pbe_WithSHA1And2_Key_TripleDES_CBC R_SHORT_READ
 F_SSL_GET_NEW_SESSION           NID_pbe_WithSHA1And3_Key_TripleDES_CBC R_SSL_SESSION_ID_IS_DIFFERENT
 F_SSL_NEW                       NID_pbe_WithSHA1And40BitRC2_CBC        R_UNABLE_TO_EXTRACT_PUBLIC_KEY
 F_SSL_READ                      NID_pbe_WithSHA1And40BitRC4            R_UNKNOWN_REMOTE_ERROR_TYPE
 F_SSL_RSA_PRIVATE_DECRYPT       NID_pbes2                              R_UNKNOWN_STATE
 F_SSL_RSA_PUBLIC_ENCRYPT        NID_pbmac1                             R_X509_LIB
 F_SSL_SESSION_NEW               NID_pkcs                               SENT_SHUTDOWN
 F_SSL_SESSION_PRINT_FP          NID_pkcs3                              SESSION_ASN1_VERSION
 F_SSL_SET_FD                    NID_pkcs7                              SESS_CACHE_BOTH
 F_SSL_SET_RFD                   NID_pkcs7_data                         SESS_CACHE_CLIENT
 F_SSL_SET_WFD                   NID_pkcs7_digest                       SESS_CACHE_NO_AUTO_CLEAR
 F_SSL_USE_CERTIFICATE           NID_pkcs7_encrypted                    SESS_CACHE_NO_INTERNAL
 F_SSL_USE_CERTIFICATE_ASN1      NID_pkcs7_enveloped                    SESS_CACHE_NO_INTERNAL_LOOKUP
 F_SSL_USE_CERTIFICATE_FILE      NID_pkcs7_signed                       SESS_CACHE_NO_INTERNAL_STORE
 F_SSL_USE_PRIVATEKEY            NID_pkcs7_signedAndEnveloped           SESS_CACHE_OFF
 F_SSL_USE_PRIVATEKEY_ASN1       NID_pkcs8ShroudedKeyBag                SESS_CACHE_SERVER
 F_SSL_USE_PRIVATEKEY_FILE       NID_pkcs9                              SSL3_VERSION
 F_SSL_USE_RSAPRIVATEKEY         NID_pkcs9_challengePassword            SSLEAY_BUILT_ON
 F_SSL_USE_RSAPRIVATEKEY_ASN1    NID_pkcs9_contentType                  SSLEAY_CFLAGS
 F_SSL_USE_RSAPRIVATEKEY_FILE    NID_pkcs9_countersignature             SSLEAY_DIR
 F_WRITE_PENDING                 NID_pkcs9_emailAddress                 SSLEAY_PLATFORM
 GEN_DIRNAME                     NID_pkcs9_extCertAttributes            SSLEAY_VERSION
 GEN_DNS                         NID_pkcs9_messageDigest                ST_ACCEPT
 GEN_EDIPARTY                    NID_pkcs9_signingTime                  ST_BEFORE
 GEN_EMAIL                       NID_pkcs9_unstructuredAddress          ST_CONNECT
 GEN_IPADD                       NID_pkcs9_unstructuredName             ST_INIT
 GEN_OTHERNAME                   NID_private_key_usage_period           ST_OK
 GEN_RID                         NID_rc2_40_cbc                         ST_READ_BODY
 GEN_URI                         NID_rc2_64_cbc                         ST_READ_HEADER
 GEN_X400                        NID_rc2_cbc                            TLS1_1_VERSION
 LIBRESSL_VERSION_NUMBER         NID_rc2_cfb64                          TLS1_2_VERSION
 MBSTRING_ASC                    NID_rc2_ecb                            TLS1_3_VERSION
 MBSTRING_BMP                    NID_rc2_ofb64                          TLS1_VERSION
 MBSTRING_FLAG                   NID_rc4                                TLSEXT_STATUSTYPE_ocsp
 MBSTRING_UNIV                   NID_rc4_40                             VERIFY_CLIENT_ONCE
 MBSTRING_UTF8                   NID_rc5_cbc                            VERIFY_FAIL_IF_NO_PEER_CERT
 MIN_RSA_MODULUS_LENGTH_IN_BYTES NID_rc5_cfb64                          VERIFY_NONE
 MODE_ACCEPT_MOVING_WRITE_BUFFER NID_rc5_ecb                            VERIFY_PEER
 MODE_AUTO_RETRY                 NID_rc5_ofb64                          V_OCSP_CERTSTATUS_GOOD
 MODE_ENABLE_PARTIAL_WRITE       NID_ripemd160                          V_OCSP_CERTSTATUS_REVOKED
 MODE_RELEASE_BUFFERS            NID_ripemd160WithRSA                   V_OCSP_CERTSTATUS_UNKNOWN
 NID_OCSP_sign                   NID_rle_compression                    WRITING
 NID_SMIMECapabilities           NID_rsa                                X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT
 NID_X500                        NID_rsaEncryption                      X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS
 NID_X509                        NID_rsadsi                             X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS
 NID_ad_OCSP                     NID_safeContentsBag                    X509_CHECK_FLAG_NO_WILDCARDS
 NID_ad_ca_issuers               NID_sdsiCertificate                    X509_CHECK_FLAG_SINGLE_LABEL_SUBDOMAINS
 NID_algorithm                   NID_secretBag                          X509_LOOKUP
 NID_authority_key_identifier    NID_serialNumber                       X509_PURPOSE_ANY
 NID_basic_constraints           NID_server_auth                        X509_PURPOSE_CRL_SIGN
 NID_bf_cbc                      NID_sha                                X509_PURPOSE_NS_SSL_SERVER
 NID_bf_cfb64                    NID_sha1                               X509_PURPOSE_OCSP_HELPER
 NID_bf_ecb                      NID_sha1WithRSA                        X509_PURPOSE_SMIME_ENCRYPT
 NID_bf_ofb64                    NID_sha1WithRSAEncryption              X509_PURPOSE_SMIME_SIGN
 NID_cast5_cbc                   NID_shaWithRSAEncryption               X509_PURPOSE_SSL_CLIENT
 NID_cast5_cfb64                 NID_stateOrProvinceName                X509_PURPOSE_SSL_SERVER
 NID_cast5_ecb                   NID_subject_alt_name                   X509_PURPOSE_TIMESTAMP_SIGN
 NID_cast5_ofb64                 NID_subject_key_identifier             X509_TRUST_COMPAT
 NID_certBag                     NID_surname                            X509_TRUST_EMAIL
 NID_certificate_policies        NID_sxnet                              X509_TRUST_OBJECT_SIGN
 NID_client_auth                 NID_time_stamp                         X509_TRUST_OCSP_REQUEST
 NID_code_sign                   NID_title                              X509_TRUST_OCSP_SIGN
 NID_commonName                  NID_undef                              X509_TRUST_SSL_CLIENT
 NID_countryName                 NID_uniqueIdentifier                   X509_TRUST_SSL_SERVER
 NID_crlBag                      NID_x509Certificate                    X509_TRUST_TSA
 NID_crl_distribution_points     NID_x509Crl                            X509_V_FLAG_ALLOW_PROXY_CERTS
 NID_crl_number                  NID_zlib_compression                   X509_V_FLAG_CB_ISSUER_CHECK
 NID_crl_reason                  NOTHING                                X509_V_FLAG_CHECK_SS_SIGNATURE
 NID_delta_crl                   OCSP_RESPONSE_STATUS_INTERNALERROR     X509_V_FLAG_CRL_CHECK
 NID_des_cbc                     OCSP_RESPONSE_STATUS_MALFORMEDREQUEST  X509_V_FLAG_CRL_CHECK_ALL
 NID_des_cfb64                   OCSP_RESPONSE_STATUS_SIGREQUIRED       X509_V_FLAG_EXPLICIT_POLICY
 NID_des_ecb                     OCSP_RESPONSE_STATUS_SUCCESSFUL        X509_V_FLAG_EXTENDED_CRL_SUPPORT
 NID_des_ede                     OCSP_RESPONSE_STATUS_TRYLATER          X509_V_FLAG_IGNORE_CRITICAL
 NID_des_ede3                    OCSP_RESPONSE_STATUS_UNAUTHORIZED      X509_V_FLAG_INHIBIT_ANY
 NID_des_ede3_cbc                OPENSSL_BUILT_ON                       X509_V_FLAG_INHIBIT_MAP
 NID_des_ede3_cfb64              OPENSSL_CFLAGS                         X509_V_FLAG_NOTIFY_POLICY
 NID_des_ede3_ofb64              OPENSSL_DIR                            X509_V_FLAG_POLICY_CHECK
 NID_des_ede_cbc                 OPENSSL_ENGINES_DIR                    X509_V_FLAG_POLICY_MASK
 NID_des_ede_cfb64               OPENSSL_PLATFORM                       X509_V_FLAG_TRUSTED_FIRST
 NID_des_ede_ofb64               OPENSSL_VERSION                        X509_V_FLAG_USE_CHECK_TIME
 NID_des_ofb64                   OPENSSL_VERSION_NUMBER                 X509_V_FLAG_USE_DELTAS
 NID_description                 OP_ALL                                 X509_V_FLAG_X509_STRICT
 NID_desx_cbc                    OP_ALLOW_NO_DHE_KEX                    X509_V_OK
 NID_dhKeyAgreement              OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION   XN_FLAG_COMPAT
 NID_dnQualifier                 OP_CIPHER_SERVER_PREFERENCE            XN_FLAG_DN_REV
 NID_dsa                         OP_CISCO_ANYCONNECT                    XN_FLAG_DUMP_UNKNOWN_FIELDS
 NID_dsaWithSHA                  OP_COOKIE_EXCHANGE                     XN_FLAG_FN_ALIGN
 NID_dsaWithSHA1                 OP_CRYPTOPRO_TLSEXT_BUG                XN_FLAG_FN_LN
 NID_dsaWithSHA1_2               OP_DONT_INSERT_EMPTY_FRAGMENTS         XN_FLAG_FN_MASK
 NID_dsa_2                       OP_EPHEMERAL_RSA                       XN_FLAG_FN_NONE
 NID_email_protect               OP_LEGACY_SERVER_CONNECT               XN_FLAG_FN_OID
 NID_ext_key_usage               OP_MICROSOFT_BIG_SSLV3_BUFFER          XN_FLAG_FN_SN
 NID_ext_req                     OP_MICROSOFT_SESS_ID_BUG               XN_FLAG_MULTILINE
 NID_friendlyName                OP_MSIE_SSLV2_RSA_PADDING              XN_FLAG_ONELINE
 NID_givenName                   OP_NETSCAPE_CA_DN_BUG                  XN_FLAG_RFC2253
 NID_hmacWithSHA1                OP_NETSCAPE_CHALLENGE_BUG              XN_FLAG_SEP_COMMA_PLUS
 NID_id_ad                       OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG     XN_FLAG_SEP_CPLUS_SPC
 NID_id_ce                       OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG    XN_FLAG_SEP_MASK
 NID_id_kp                       OP_NON_EXPORT_FIRST                    XN_FLAG_SEP_MULTILINE
 NID_id_pbkdf2                   OP_NO_CLIENT_RENEGOTIATION             XN_FLAG_SEP_SPLUS_SPC
 NID_id_pe                       OP_NO_COMPRESSION                      XN_FLAG_SPC_EQ
 NID_id_pkix                     OP_NO_ENCRYPT_THEN_MAC                 

/);

my @missing;
my %h = map { $_=>1 } @Net::SSLeay::EXPORT_OK;

for (@c) {
  like(eval("&Net::SSLeay::$_; 'ok'") || $@, qr/^(ok|Your vendor has not defined SSLeay macro.*)$/, "$_");
  push(@missing, $_) unless $h{$_};
}

is(join(",", sort @missing), '', 'constants missing in @EXPORT_OK count='.scalar(@missing));

